# 关键词回复配置文件
# 格式: 关键词: 回复内容

keywords:
  - trigger: "awa"
    response: "qwq"
    
  - trigger: "qwq"
    response: "awa"
    
  - trigger: "uwu"
    response: "QAQ"
    
  - trigger: "QAQ"
    response: "uwu"
    
  - trigger: "owo"
    response: "xwx"
    
  - trigger: "sws"
    response: "zwz"
    
  - trigger: "xwx"
    response: "owo"
    
  - trigger: "zwz"
    response: "sws"
    
  - trigger: "hwh"
    response: "xvx"
    
  - trigger: "xvx"
    response: "hwh"
    
  - trigger: "ywy"
    response: "zaz"
    
  - trigger: "zaz"
    response: "ywy"
    
  - trigger: "mwm"
    response: "nwn"
    
  - trigger: "nwn"
    response: "mwm"
    
  - trigger: "qvq"
    response: "pwp"
    
  - trigger: "pwp"
    response: "qvq"
    
  - trigger: "666"
    response: "6969"
    
  - trigger: "6969"
    response: "666"
    
  - trigger: "Orz"
    response: "OvO"
    
  - trigger: "OvO"
    response: "Orz"
    
  - trigger: "XD"
    response: "DX"
    
  - trigger: "DX"
    response: "XD"
    
  - trigger: "中"
    response: "太中嘞"
    
  - trigger: "太中嘞"
    response: "中"
    
  - trigger: "俺不中嘞"
    response: "不中"
    
  - trigger: "不中"
    response: "俺不中嘞"
    
  - trigger: ">_<"
    response: "o_o"
    
  - trigger: "o_o"
    response: ">_<"
    
  - trigger: "0w0"
    response: "0v0"
    
  - trigger: "0v0"
    response: "0w0"
    
  - trigger: "@_@"
    response: "#_#"
    
  - trigger: "#_#"
    response: "@_@"
    
  - trigger: "*_*"
    response: "&_&"
    
  - trigger: "&_&"
    response: "*_*"
    
  - trigger: "好色"
    response: "喜欢~"
    
  - trigger: "好涩"
    response: "喜欢~"
    
  - trigger: "嗷呜"
    response: "呜嗷"
    
  - trigger: "呜嗷"
    response: "嗷呜"
    
  - trigger: "毛毛"
    response: "爪爪"
    
  - trigger: "爪爪"
    response: "毛毛"
    
  - trigger: "臭臭的"
    response: "尾巴"
    
  - trigger: "吸烟"
    response: "唔!烟,吸烟?不准!"
    
  - trigger: "?"
    response: "脑子里只剩问号惹~"